services:
    ligneus_exception_tracker.exception_listener:
        class: Ligneus\ExceptionTrackerBundle\EventListener\ExceptionListener
        arguments:
            - %ligneus.exception.tracker_endpoint%
            - %ligneus.exception.app_key%
            - %kernel.environment%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
