services:
    phylax_exception_tracker.exception_listener:
        class: Phylax\PhylaxTrackerBundle\EventListener\ExceptionListener
        arguments:
            - %phylax.exception.tracker_endpoint%
            - %phylax.exception.app_key%
            - %kernel.environment%
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
